services:
  hub_django:
    build:
      context: .
      dockerfile: Dockerhub
    ports:
      - "3000:3000"

  app3:
    build:
      context: .
      dockerfile: app3
    ports:
      - "3001:3001"

  app1:
    build:
      context: .
      dockerfile: app1
    ports:
      - "8001:8001"

  app2:
    build:
      context: .
      dockerfile: app2
    ports:
      - "8002:8002"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_hub.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hub_django
      - app1
      - app2
      - app3
